version: "2.4"

services:

  # Adobe ColdFusion 2021 site.
  cfml2021:
    image: "ortussolutions/commandbox:adobe2021"
    ports:
      - "8021:8080"
    volumes:
      - "./app-2021:/app"
    environment:
      BOX_SERVER_PROFILE: "development"
      cfconfig_adminPassword: "password"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "echo hello"

  # Adobe ColdFusion 2023 site.
  cfml2023:
    image: "ortussolutions/commandbox:adobe2023"
    ports:
      - "8023:8080"
    volumes:
      - "./app-2023:/app"
    environment:
      BOX_SERVER_PROFILE: "development"
      cfconfig_adminPassword: "password"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "echo hello"

  # MySQL server.
  mysql:
    image: "mysql:8.0.28-oracle"
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_DATABASE: "demo"
      MYSQL_ROOT_PASSWORD: "password"
    healthcheck:
      test: "echo hello"
